# Generated by Django 4.2.6 on 2023-10-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Affilation', models.CharField(max_length=150)),
                ('Simplified_Affiliation_for_collapsing', models.CharField(max_length=225)),
            ],
        ),
    ]
