# Generated by Django 4.2.6 on 2023-11-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='store_in_database',
            field=models.BooleanField(default=True),
        ),
    ]
